#!/bin/bash


export USE_AZURE_OPENAI=False
export USE_AZURE_AD=False
export AZURE_OPENAI_API_VERSION=2024-02-15-preview
export AZURE_OPENAI_DEPLOYMENT_NAME=dall-e-3
export AZURE_OPENAI_ENDPOINT=https://petclinic.openai.azure.com
export AZURE_OPENAI_DALLE_ENDPOINT=https://petclinic.openai.azure.com
export AZURE_OPENAI_DALLE_DEPLOYMENT_NAME=dall-e-3
export OPENAI_API_KEY=$OPENAI_API_KEY
export OPENAI_ORG_ID=org-MQENs1E0HzS2Bg6rgEc4jkR6
export AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY

echo $USE_AZURE_OPENAI
echo $USE_AZURE_AD
echo $AZURE_OPENAI_API_VERSION
echo $AZURE_OPENAI_DEPLOYMENT_NAME
echo $AZURE_OPENAI_DALLE_ENDPOINT
echo $AZURE_OPENAI_DALLE_DEPLOYMENT_NAME
echo $OPENAI_ORG_ID
echo $OPENAI_API_KEY
echo $AZURE_OPENAI_ENDPOINT


